const Sdata = [
  {
    id: 1,
    title: "Oriando",
    image: "/images/dest-1.jpg",
    desc: "Because The Peninsula Chicago understands that each guest’s time is precious, the hotel offers ‘Peninsula Time,’ a unique check-in/check-out experience offering guests maximum flexibility. With ‘Peninsula Time,’ by prior arrangement, guests may check in and out at with flexibility and no additional fee. Black-out dates apply for Peninsula Time and is only applicable to particular booking channels. Kindly check the terms and conditions at the time of booking or consult with our reservations agent or your preferred travel advisor.",
    sidepara: "With views overlooking Michigan Avenue and a bright and airy atmosphere, the spacious one-bedroom Michigan Avenue Suites are the most popular among guests. Separate bedroom and living areas offer contemporary interiors with a cosmopolitan attitude and are divided by an artisan crafted glass wall. The lush sofa in the living area can transform into a pullout sofa-bed in the living room, making this an ideal choice for families.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
  {
    id: 2,
    title: "Miami",
    image: "/images/dest-2.jpg",
    desc: " The Peninsula Chicago inspires travelers to embark on a long weekend or weekday getaway with More Time…With Our Compliments, which offers a third night complimentary when booking a minimum stay of three consecutive nights.",
    sidepara: "The Peninsula recognizes the critical importance of being together with loved ones, especially during challenging times. Our new booking benefit is designed to make stays with family and friends easier than ever. When you reserve one of our elegantly appointed rooms or suites directly via our website, you will also be able to select and confirm a connecting room or suite. On your next visit, make more time to connect with the security of knowing you’ll have a shared space to enjoy.",
  },
  {
    id: 3,
    title: "Los Angeles",
    image: "/images/dest-3.jpg",
    desc: "The spacious Executive Suites occupy corners of the hotel, offering picturesque city views from large windows.",
    sidepara: "Reserve a suite online and take advantage of additional benefits with the Suite Escape offer, including daily breakfast and a hotel credit.",
  },
  {
    id: 4,
    title: "San Diego",
    image: "/images/dest-4.jpg",
    desc: "The Peninsula recognizes the critical importance of being together with loved ones, especially during challenging times. Our new booking benefit is designed to make stays with family and friends easier than ever. When you reserve one of our elegantly appointed rooms or suites directly via our website, you will also be able to select and confirm a connecting room or suite. On your next visit, make more time to connect with the security of knowing you’ll have a shared space to enjoy.",
    sidepara: "The Peninsula recognizes the critical importance of being together with loved ones, especially during challenging times. Our new booking benefit is designed to make stays with family and friends easier than ever.",
  },
  {
    id: 5,
    title: "Houston",
    image: "/images/dest-5.jpg",
    desc: "In a city renowned for its legacy of forward-thinking design and architecture, The Peninsula Chicago sets a new standard for accommodations in Chicago. Designed with the luxury traveler in mind, the guest rooms showcase The Peninsula's evolution of design of luxury and enhance every guest's stay with ease, elegance and the ultimate personalization.",
    sidepara: "Three cityscapes: Michigan Ave/Superior Ave, Superior Ave/Rush St or Rush St/Chicago Ave",
  },
  {
    id: 6,
    title: "New York",
    image: "/images/dest-6.jpg",
    desc: "The Peninsula Chicago is family-friendly, offering fascinating Peninsula Academy programs especially for children and tailoring stays to appeal to even the youngest of guests.",
    sidepara: "When you reserve one of our elegantly appointed rooms or suites directly via our website, you will also be able to select and confirm a connecting room or suite.",
  },
  {
    id: 7,
    title: "Los Angeles",
    image: "/images/dest-3.jpg",
    desc: "The spacious Executive Suites occupy corners of the hotel, offering picturesque city views from large windows.",
    sidepara: "On your next visit, make more time to connect with the security of knowing you’ll have a shared space to enjoy..",
  },
  {
    id: 8,
    title: "San Diego",
    image: "/images/dest-4.jpg",
    desc: "The Peninsula recognizes the critical importance of being together with loved ones, especially during challenging times. Our new booking benefit is designed to make stays with family and friends easier than ever. When you reserve one of our elegantly appointed rooms or suites directly via our website, you will also be able to select and confirm a connecting room or suite. On your next visit, make more time to connect with the security of knowing you’ll have a shared space to enjoy.",
    sidepara: "Allow us to take care of more than just your room with our Drive, Dine, Delight offer. Indulge in daily breakfast and worry-free parking",
  },
  {
    id: 9,
    title: "Houston",
    image: "/images/dest-5.jpg",
    desc: "In a city renowned for its legacy of forward-thinking design and architecture, The Peninsula Chicago sets a new standard for accommodations in Chicago. Designed with the luxury traveler in mind, the guest rooms showcase The Peninsula's evolution of design of luxury and enhance every guest's stay with ease, elegance and the ultimate personalization.",
    sidepara: "Three cityscapes: Michigan Ave/Superior Ave, Superior Ave/Rush St or Rush St/Chicago Ave",
  },
  {
    id: 10,
    title: "New York",
    image: "/images/dest-6.jpg",
    desc: "The Peninsula Chicago is family-friendly, offering fascinating Peninsula Academy programs especially for children and tailoring stays to appeal to even the youngest of guests.",
    sidepara: " so that you can spend more time luxuriating in relaxation or adventuring into the city..",
  },
]

export default Sdata
