const BlogData = [
  {
    id: 1,
    date: "January 01, 2020",
    catgeory: "Business ",
    title: "The Most Advance Business Plan",
    cover: "/images/singlepage/blog-1.jpg",
    para: "With views overlooking Michigan Avenue and a bright and airy atmosphere, the spacious one-bedroom Michigan Avenue Suites are the most popular among guests.",
    desc: "Separate bedroom and living areas offer contemporary interiors with a cosmopolitan attitude and are divided by an artisan crafted glass wall ",
  },
  {
    id: 2,
    date: "January 15, 2021",
    catgeory: "Traveling",
    title: "Beautiful Home Page",
    cover: "/images/singlepage/blog-2.jpg",
    para: "The lush sofa in the living area can transform into a pullout sofa-bed in the living room, making this an ideal choice for families.",
    desc: " Accessible rooms available. Deluxe King Rooms can connect to Deluxe King Suite or Executive Suite. ",
  },
  {
    id: 3,
    date: "January 21, 2018",
    catgeory: "Developement",
    title: "Modern Design Concept",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Deluxe King Guestrooms offer delightful westward city views overlooking Rush Street or south overlooking Superior Street while Deluxe Double Guestrooms offers views overlooking Michigan Avenue.",
    desc: " Deluxe Double Rooms can connect to Grand Premier King Room or Accessible Grand Deluxe King Room.",
  },
  {
    id: 4,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Grand Deluxe Guestrooms feature magnificent views of Chicago's premier shopping district, Michigan Avenue",
    desc: " the historic Water Tower, or westward city views  to enjoy Chicago's sunsets. ",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Investment Planning",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Grand Premier Double Guestrooms feature westward city views overlooking Rush Street and Chicago's sunsets. ",
    desc: " Grand Premier Double Rooms can connect to a Deluxe Suite.",
  },
  {
    id: 6,
    date: "January 18, 2021",
    catgeory: "Web Developement",
    title: "Why you Should Always First",
    cover: "/images/singlepage/blog-6.jpg",
    para: "The spacious Executive Suites occupy corners of the hotel, offering picturesque city views from large windows.",
    desc: "Executive Suites can connect to Deluxe King Rooms. ",
  },
  {
    id: 7,
    date: "January 12, 2014",
    catgeory: "Business Strategy",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-1.jpg",
    para: "The Lake Suite is 2,561 sq ft (232.26 sq m) and features an exquisite reception area for welcoming up to 10 guests. ",
    desc: " With sweeping views of the Windy City on the North, East, and South sides of the building, this suite includes two bedrooms, two marble bathrooms, a powder room",
  },
  {
    id: 8,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-4.jpg",
    para: "The Lake Suite also includes a home theater in the living room area and kitchenette adjacent to the dining room.",
    desc: "For added security and privacy, the Lake Suite can be blocked off from the rest of the hotel. ",
  },
  {
    id: 9,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Investment Planning",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Grand Deluxe Guestrooms feature magnificent views of Chicago's premier shopping district",
    desc: "Accessible rooms available. Grand Deluxe King Rooms can connect to a Premier Deluxe Suite or Accessible Deluxe King Suite. ",
  },
]

export default BlogData
